### ISSUE TITLE
Filter: File Contents

### ISSUE THREAD

**Issue by ralle12345** [tfeldmann/organize#10]
Hi @tfeldmann,
I like your organize tool. I would however like to see matching for file contents like File Juggler does.

There you can match things like a date found in the document and use it as a pattern for renaming or match for specific Words appearing in the file. This would be extremely useful for automatically sorting OCRed scanned documents.

What do you think?

**Comment by tfeldmann** [comment]
This is certainly useful and should be included. Thank you for the suggestion, I added it to my todo list!

**Comment by fgma** [comment]
Merged in f314585. Issue may be closed.

**Comment by tfeldmann** [comment]
This is now released in v1.8.0
