### ISSUE TITLE
Install via homebrew

### ISSUE THREAD

**Issue by quintrino** [tfeldmann/organize#100]
Hi, 

Have you considered submitting this to Homebrew? 
I'm not sure if you meet the criteria here https://docs.brew.sh/Acceptable-Formulae or if it would have to be a tap but it would be super cool to install via the brew command.

**Comment by tfeldmann** [comment]
Hi, I agree, that would be nice. I always thought homebrew discourages python packages which can be normally installed via pip but I now I can't find any documents that say so. I'll look into this!

On a side note: Personally I'm using pipx to install python applications - maybe that is something for you?

**Comment by quintrino** [comment]
Interesting. 

I'm still trying to stick to installing most things via brew for the moment. But if I end up a heap of python tools all tempting me I'll give it a look.

**Comment by quintrino** [comment]
@tfeldmann I put through a PR and got it added to Homebrew. 
https://github.com/Homebrew/homebrew-core/pull/74942

It's now installable via 
`brew install organize-tool`

**Comment by tfeldmann** [comment]
Thank you a lot @quintrino, that's great!
