### ISSUE TITLE
Feature Request: variables in rule file

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#114]
I am using organize to move files from and to iCloud.
Unfortunately the local path of the iCloud is pretty lengthy which make the rule look ugly.
e.g 
```yaml
- Move: '~/Library/MobileDocuments/com~apple~CloudDocs/Documents/Organize/filed_docs/Rechnungen/{python.year}/'
```

I would prefer something like

```
DESTINATION='~/Library/Mobile Documents/com~apple~CloudDocs/Documents/Organize/filed_docs'
rules:

      - Move: "{DESTINATION}/Rechnungen/{python.year}/"
```

**Comment by tfeldmann** [comment]
Yes, good one! It's on the todo list. I'll keep this issue open until this is implemented.

**Comment by Marty56** [comment]
Good that you understood the idea. Allthough I did not manage to format the code snippets correctly.

**Comment by Marty56** [comment]
I use a workaround now
In the environment file I have defined a variable, e.g. DESTINATION

```
  filters:
      - python: |
          import os
          return {"help": {
                    "destination":os.environ['DESTINATION']
                      }

      - Move: '{python.help.destination}/...

```

**Comment by Marty56** [comment]
SInce environment variable are now working also under macOS this issue can be closed TMH.
