### ISSUE TITLE
Feature request macOS tags should support placeholders

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#119]
the following code 
```
      - macos_tags:
        - '{python.year[0]} Steuer'
```
is creating the following tag
{python.year[0]} Steuer

the desired output should be the contents for the placeholders in my example
2020 Steuer

**Comment by tfeldmann** [comment]
Available in the newest version v1.10.1 👍

**Comment by Marty56** [comment]
Minor issue
tag defintion that is starting with a placeholder is not working.
e.g.

      - macos_tags:
           - UW {python.help.period} (green) --> working
           - {python.help.period} UW (green) --> not working

**Comment by tfeldmann** [comment]
Yes this has to do with the yaml syntax. To be safe, just wrap everything in `""`. 

```yaml
- "{python.help.period} (green)"
```

should work.

**Comment by Marty56** [comment]
Ok. This is very acceptable.
Thanks for the great support.

**Comment by tfeldmann** [comment]
Np!
