### ISSUE TITLE
Environment variable in folder path is not working in MacOS

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#121]
In the document it is stated
`You can use environment variables in your folder names. On windows this means you can use %public%/Desktop, %APPDATA%, %PROGRAMDATA% etc.`

I tried various variations with respect of a potential syntax e.g.
$ENVIROMENTVAR/....
${ENVIROMENTVAR}/....
%ENVIROMENTVAR%/....

Either I received a syntax check error or I received ${ENVIROMENTVAR}/.... folder not found

**Comment by tfeldmann** [comment]
The `$VAR` syntax works, but the error message shows the orginal string, not the expanded one. Fixed in the next version!

**Comment by tfeldmann** [comment]
New version is released.

**Comment by Marty56** [comment]
Thanks again for the fast reply.
Minor issue.
When I am using the $HOME variable within the environment file of macOS this construction is not resolve correctly.

e.g. in the .bash_profile file

export SOURCE='$HOME/Library/Mobile Documents/com~apple~CloudDocs/Document

is not working. Organizer is creating a filename that includes $HOME.
So I had to apply a workaround removing the $HOME by a dedicated folder location which makes the .bash_profile less portable.
