### ISSUE TITLE
Feature: Use python to both filter and create placeholder variables

### ISSUE THREAD

**Issue by Marty56** [tfeldmann/organize#125]
It is possible to use python in the filter section to create placeholder variables.
Also it is possible to implement filters and return either False oder True depending on the python filter.

But to my current understanding I see no way to combine both function within python because I can either return the filter value, e.g. False or a the placeholder variables.

**Comment by tfeldmann** [comment]
You should be able to return placeholder variables on a match and 'False' or 'None' otherwise.

**Comment by Marty56** [comment]
I was not able to return formats like. I have tried various return constructs (see below) but none of them was working.

```
          return {"filter": filter,
                  "year":path.stem[0:4],
                  "result":False
                 }
--> syntax ok. But not working
or 
          return {False,
                  "year":path.stem[0:4],
                  "result":False
                 }
--> syntax not ok.

```

**Comment by tfeldmann** [comment]
Try either

```python
return False
```
Or

```
return {"your_placeholder": "value"}
```

**Comment by Marty56** [comment]
I have tried this and this works but only exclusively.
So either placeholder or False/True not both.

**Comment by Marty56** [comment]
I made a mistake in my reasoning. Please close this issue
