### ISSUE TITLE
Filter: Class 'CreationDate'

### ISSUE THREAD

**Issue by pat-s** [tfeldmann/organize#13]
Hi! Loving your project.

Would it be possible to add a class "Date" which stores the creation date? This could be used as a filter and a var for actions, e.g. when organizing files by date 

`Rename: {filename}-{date}.{extension}`

**Comment by tfeldmann** [comment]
Thanks!
Maybe you can use the `LastModified` filter (https://organize.readthedocs.io/en/latest/page/filters.html#lastmodified).

Back then I didn't add a filter for the file creation date because of the ambiguous behaviour of `os.stat` in python:

```
st_ctime:
  Platform dependent:
   - the time of most recent metadata change on Unix,
   - the time of creation on Windows, expressed in seconds.
```

Maybe I'll add it in the future.

**Comment by tfeldmann** [comment]
This is now implemented in the new version 👍
