### ISSUE TITLE
Add filter for Date Added

### ISSUE THREAD

**Issue by dunxd** [tfeldmann/organize#137]
Files that have just been downloaded may have a Created or Modified date that is much older. Allow using the Date Added field to filter based on when a file was added to the folder.

**Comment by dunxd** [comment]
Should have mentioned this may only be possible for macos.  An example of how to get the Date Added property for a file using Python is at https://stackoverflow.com/a/30969532/246433

**Comment by dunxd** [comment]
I had a go at writing a filter for Date Added, based on created.py and last_modified.py, but I am not a python programmer (or any kind of coder really) so don't really know how I would go about incorporate this into organize and test it.

[date_added.txt](https://github.com/tfeldmann/organize/files/6812125/date_added.txt)

**Comment by tfeldmann** [comment]
This is now added and will be released in the next version.
You can try it out in the development version:

```
pip3 install git+https://github.com/tfeldmann/organize.git
```

**Comment by tfeldmann** [comment]
Closing this as it was released in v2.1.0.
