### ISSUE TITLE
Zero padding for month and day returns

### ISSUE THREAD

**Issue by dunxd** [tfeldmann/organize#138]
Created and LastModified return {created.month} and {created.day} without leading zeros for dates less than 10.  E.g. 1st January 2021 is returned by {created.year}/{created.month}/{created.day} as 2021/1/1.

Padding of the month or dates less than 10 is useful for sorting folders - e.g. 2021/01/01 is better as otherwise October folder immediately follows January folder.

What is the best way to create/use folders like this with Organize?

**Comment by dunxd** [comment]
Ok - I spotted the note about the syntax to get the padding in the Advanced Usage section of the readme.  I would suggest including this in the documentation for the Created and LastModified filters, as it is not easy to find if you don't remember it.  And are there additional syntax modifiers?

**Comment by tfeldmann** [comment]
All the standard modifiers known from `str.format`are available (https://docs.python.org/3/library/string.html#formatspec). In the future a different template engine is planned (Jinja2) so this might stop working.
