### ISSUE TITLE
`DistutilsError` saying there's a sandbox violation.

### ISSUE THREAD

**Issue by parsanoori** [tfeldmann/organize#139]
I'm on macos.
Ran `pip install organize-tool` but get this error:
```
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/Users/parsa/Library/Caches/com.apple.python/private/var/folders/xn/96skgj1d0wn4_9hzzm66xwlh0000gn/T/easy_install-iswwqubq', 511) {}
```
Could install it as root but it's not good to.
How can I resolve that issue ?

**Comment by tfeldmann** [comment]
Which macOS version are you on? Can you do an `pip install -U pip` before?

**Comment by parsanoori** [comment]
I don't know how But I finally got through it. 
Thank you for your help.
