### ISSUE TITLE
Feature request: Get the file size in units other than bytes

### ISSUE THREAD

**Issue by OmarNamis** [tfeldmann/organize#141]
Currently, Organize only provides the placeholder variable {filesize.bytes} which returns the file size in bytes.

I want to be able to get the file size in other units, such as megabytes and gigabytes.

**Comment by tfeldmann** [comment]
This is coming in v2.

**Comment by tfeldmann** [comment]
v2 is now released. Check out the [size filter](https://organize.readthedocs.io/en/latest/filters/#size) for the new options 👍
