### ISSUE TITLE
Rename: Remove whitespace from counter

### ISSUE THREAD

**Issue by pat-s** [tfeldmann/organize#15]
When renaming multiple files to the same filename, a counter is added. 

However, the counter automatically consists of "[whitespace]<counter>". Could the whitespace be removed?

**Comment by tfeldmann** [comment]
Good idea 👍
I just pushed 01c736c which allows to set a custom `counter_separator` in `Move`, `Copy` and `Rename` actions.

**Comment by tfeldmann** [comment]
v1.4.1 with this feature is now available on pypi 👍

**Comment by pat-s** [comment]
Thanks a lot! This project has really high potential. Keep it up!

**Comment by iburunat** [comment]
This tool is really excellent and useful, thank you for developing it and for keeping it up. Regarding the counter, is it possible to have counter on all renamed files (not just starting from the second), as to not leave any file without a counter. The counter-less file is placed at the end of the list of files when ordered by name, when it would be desirable that stands at the beginning). I am not sure if this is possible, couldn't find it on the docs. Thanks in advance for any tips.

nameoffile_02.jpg (not nameoffile 2.jpg
