### ISSUE TITLE
Duplicate filter can offer unpredictable results in folders with multiples copies of a single file

### ISSUE THREAD

**Issue by elsatch** [tfeldmann/organize#158]
I have used organize to sort and rename files. After several runs, I created a few duplicates. As I tried to remove the dupes with the built-in filter, the simulations worried me a bit. I created a simplified example to demonstrate this behavior.

## Initial configuration
You have a folder with several copies of the same file. There is an original file and several copies of the same file with numbers appended at the end. For this example, I created a testfile.txt under testdupes folder. Content of the file is "Hello World!". Then I copied the file 5 times using the Finder (on Mac).

### Organize rule
This is the organize rule I used to match the duplicate files:
```yaml
- folders: ~/testdupes/**/*
    filters:
      - duplicate
    actions:
      - echo: "{path} is a duplicate of {duplicate}"
```
## Initial test
```
 ~ % vi testdupes/tesfile.txt
(Files copied on Finder)
 ~ % cd testdupes 
testdupes % ls -la
total 48
drwxr-xr-x   8 user  staff   256 27 ene 11:11 .
drwxr-xr-x+ 53 user  staff  1696 27 ene 11:10 ..
-rw-r--r--   1 user  staff    13 27 ene 11:10 tesfile_copy_1.txt
-rw-r--r--   1 user  staff    13 27 ene 11:10 tesfile_copy_2.txt
-rw-r--r--   1 user  staff    13 27 ene 11:10 tesfile_copy_3.txt
-rw-r--r--   1 user  staff    13 27 ene 11:10 tesfile_copy_4.txt
-rw-r--r--@  1 user  staff    13 27 ene 11:10 tesfile_copy_5.txt
-rw-r--r--   1 user  staff    13 27 ene 11:10 tesfile_orig.txt
```

Then I run the organize sim command:
```
testdupes % organize sim            
False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /Users/user/testdupes:
  File tesfile_copy_2.txt:
    - [Echo] /Users/user/testdupes/tesfile_copy_2.txt is a duplicate of /Users/user/testdupes/tesfile_copy_1.txt
  File tesfile_copy_3.txt:
    - [Echo] /Users/user/testdupes/tesfile_copy_3.txt is a duplicate of /Users/user/testdupes/tesfile_copy_2.txt
  File tesfile_copy_4.txt:
    - [Echo] /Users/user/testdupes/tesfile_copy_4.txt is a duplicate of /Users/user/testdupes/tesfile_copy_3.txt
  File tesfile_copy_5.txt:
    - [Echo] /Users/user/testdupes/tesfile_copy_5.txt is a duplicate of /Users/user/testdupes/tesfile_copy_4.txt
  File tesfile_orig.txt:
    - [Echo] /Users/cesargarciasaez/testdupes/tesfile_orig.txt is a duplicate of /Users/cesargarciasaez/testdupes/tesfile_copy_5.txt
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Issues detected

- Organize only looks for the first duplicate. If you have several duplicates of each other, they won't be detected as dupes of the original. 
- The order of the sort appear to be on last modified, not on creation date. This can create issues if you ask Organize to delete the duplicates. Instead of ending up with the original file, that file could be deleted and you could end up with one of the copies (but it is not easy to determine the ending name/number).
- In this particular example, if I deleted instead of echoing the name, I would have keep just: tesfile_copy_1.txt
- Note: I assume you will always retain one of the copies, but I am not sure this could not lead to a circular deletion of all duplicates, including the original file too.

## Additional tests
To verify that last modified date is the default sort order, I rename all files but the original one.
```
testdupes % mv tesfile_copy_1.txt 'testfile_orig 1.txt'
testdupes % mv tesfile_copy_2.txt 'testfile_orig 2.txt'
testdupes % mv tesfile_copy_3.txt 'testfile_orig 3.txt'
testdupes % mv tesfile_copy_4.txt 'testfile_orig 4.txt'
testdupes % mv tesfile_copy_5.txt 'testfile_orig 5.txt'
```

Then running organize sim again, would leave testfile_orig.txt untouched.

```
testdupes % organize sim                               
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /Users/user/testdupes:
  File testfile_orig 1.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 1.txt is a duplicate of /Users/user/testdupes/tesfile_orig.txt
  File testfile_orig 2.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 2.txt is a duplicate of /Users/user/testdupes/testfile_orig 1.txt
  File testfile_orig 3.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 3.txt is a duplicate of /Users/user/testdupes/testfile_orig 2.txt
  File testfile_orig 4.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 4.txt is a duplicate of /Users/user/testdupes/testfile_orig 3.txt
  File testfile_orig 5.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 5.txt is a duplicate of /Users/user/testdupes/testfile_orig 4.txt
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This test might suggest that last modified file is not tested for duplication. Is this expected behavior?

Additional run, renaming the original file. This would leave us again with testfile_orig 1.txt as the only remaining copy.

```
testdupes% mv tesfile_orig.txt testfile_true_orig.txt
testdupes % organize sim                              
False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Folder /Users/user/testdupes:
  File testfile_orig 2.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 2.txt is a duplicate of /Users/user/testdupes/testfile_orig 1.txt
  File testfile_orig 3.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 3.txt is a duplicate of /Users/user/testdupes/testfile_orig 2.txt
  File testfile_orig 4.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 4.txt is a duplicate of /Users/user/testdupes/testfile_orig 3.txt
  File testfile_orig 5.txt:
    - [Echo] /Users/user/testdupes/testfile_orig 5.txt is a duplicate of /Users/user/testdupes/testfile_orig 4.txt
  File testfile_true_orig.txt:
    - [Echo] /Users/user/testdupes/testfile_true_orig.txt is a duplicate of /Users/user/testdupes/testfile_orig 5.txt
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SIMULATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
## Final notes
I am aware that I can use the regex filter (and maybe even the filename filter) to deal with duplicates with similar names, but I am not quite sure that the duplicate filter won't cause any data loss without any extra attention in folders with several copies of the same file.

**Comment by tfeldmann** [comment]
Hey, thank you for the detailed problem description.

First off, a circular deletion of all duplicates should not be possible, one file is always left behind. The only scenario where I can see this happen is if subsequent actions overwrite / delete the left over file because the location of the file detected as the original is unexpected.

Right now the duplicate filter considers whatever file it sees first as the original file. This kind of depends on the filesystem and the python `glob.glob()` function. I see that this is not ideal so I'm open for ideas. The created date seems like a good option.

To be really flexible, I'm thinking about a `ordering` parameter like this:

```yaml
filters:
  - duplicate:
      ordering: "created" # ("lastmodified", "name", "path", custom python function?)
actions:
  - trash
```

What do you think about this?

**Comment by elsatch** [comment]
Thanks Thomas for your fast and clear response!

Your proposal would be very useful to cover several use cases involving duplicates. I am not sure about how hard would be to implement it. Checking the glob.glob() function, I see it returns a list of paths in arbitrary order. I assume you would pass that list to pathlib or os to check the creation or modification dates. Leaving this open to custom functions would make it more extensible, but I am sure most people would use the 2-3 built-in.

As I first step, may I create a pull request to update the documentation of the duplicate function and make the current behavior explicit in the description? I am looking to contribute documenting practical use cases

**Comment by tfeldmann** [comment]
Yes, that would be much appreciated! The new ordering parameter will be available in the next version of organize.

**Comment by tfeldmann** [comment]
Hey, I thought maybe you want to beta test this new feature?

```
pip3 install git+https://github.com/tfeldmann/organize.git@v2
```

The documentation for v2 is here:
https://tfeldmann.github.io/organize/filters/#duplicate

**Comment by tfeldmann** [comment]
Forgot to mention: For v2 slight adjustments in your config are needed:

https://tfeldmann.github.io/organize/updating-from-v1/

**Comment by tfeldmann** [comment]
The new version is released and has the new detection method selection in the duplicate filter ([docs](https://organize.readthedocs.io/en/latest/filters/#duplicate)). Feedback would be much appreciated!

**Comment by tfeldmann** [comment]
Yes you should probably uninstall the brew version. Maybe you can try with `python3 -m organize` in the meantime.
