### ISSUE TITLE
{path.parent}/{path.stem}

### ISSUE THREAD

**Issue by iburunat** [tfeldmann/organize#175]
As part of my old config I had:

```yaml
- shell: |
          magick "{path}" -resize '1440x1440>' "{path.parent}/{path.stem}_r.{}"
```
I suspect this syntax has changed in the last big revamping of this tool.
On which page could I find the current syntax?
Thanks!

**Comment by tfeldmann** [comment]
I just released a version which fixes some bugs in the shell action - maybe give it a try? v2.0.8 it is.

**Comment by iburunat** [comment]
Thanks, that is exactly the version I am using (just upgraded before trying).

**Comment by tfeldmann** [comment]
The problem is the `"{}"` at the end - what is this for?
Maybe escape it?

```yaml
- shell: |
          magick "{path}" -resize '1440x1440>' "{path.parent}/{path.stem}_r.{{}}"
```

**Comment by tfeldmann** [comment]
The `path` stuff should work just fine

**Comment by iburunat** [comment]
Yes, thank you. Apparently the {} never gave errors in the previous versions!
Now working, thanks again.
