### ISSUE TITLE
Migration to 2.0 - InvalidCharsInPath: contains invalid characters

### ISSUE THREAD

**Issue by ktreharrison** [tfeldmann/organize#184]
I am trying to move from 1.0 to 2.0 on my Windows 10 laptop. However, I cannot simulate or run any rules.  

The error message reads : `InvalidCharsInPath: path 'C:\Users\%USERPFOILE%\AppData\Local\organize\organize\config.yaml' contains invalid characters`

Errors are occurring at :

Python\Python310\lib\site-packages\organize\cli.py:86 in   │
│ run_local  
>  86 │   │   config = open_fs(config_dir).readtext(config_name)  

\Python\Python310\lib\site-packages\fs\base.py:691 in       ││ readtext                                                                                         │
>  691 │   │   │   self.open(                                                                    │
│    692 │   │   │   │   path, mode="rt", encoding=encoding, errors=errors, newline=newline        │
│    693 │   │   │   )                                                                             │
│    694 │   │   ) as read_file:       

Python\Python310\lib\site-packages\fs\osfs.py:640 in open        

  │ > 640 │   │   _path = self.validatepath(path)     

Python\Python310\lib\site-packages\fs\osfs.py:687 in       │
│ validatepath                                                                                     │
│ > 687 │   │   return super(OSFS, self).validatepath(path)                    

│ > 1577 │   │   │   │   raise errors.InvalidCharsInPath(path)       

How can I resolve this ? I'm I missing some dependencies ?

**Comment by tfeldmann** [comment]
Please try setting the absolute path without `%USERPFOILE%` or try `$USERPROFILE` or `{env.USERPROFILE}` instead.
There seems to be an error with the windows way of using environment variables

**Comment by tfeldmann** [comment]
If that doesn't work please try again with forward slashes, e.g. `c://Users/$USERPROFILE/AppData/...`

**Comment by tfeldmann** [comment]
I just raised an issue with the underlying filesystem library:

https://github.com/PyFilesystem/pyfilesystem2/issues/524

In the meantime you have to define an absolute path without variables. I tried it and backslashes (`C:\\Users..`) are fine.

**Comment by razielfayad** [comment]
same problem here. 
>organize sim

Traceback (most recent call last)
C:\Users\RAZIEL\AppData\Local\Programs\Python\Python310\lib\site-packages\organize\cli.py:86 in run_local
│    83 │   try:
│    84 │   │   console.info(config_path=config_path, working_dir=working_dir)
│   85 │   │   config_dir, config_name = split(config_path)
│ > 86 │   │   config = open_fs(config_dir).readtext(config_name)
│   87 │   │   os.chdir(working_dir)
│  88 │   │   core.run(rules=config, simulate=simulate) 
│   89 │   except NeedsMigrationError as e:

C:\Users\RAZIEL\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\base.py:691 in readtext                                                                                         

│    688 │   │
│    689 │   │   """
│    690 │   │   with closing(
│ >  691 │   │   │   self.open(
│    692 │   │   │   │   path, mode="rt", encoding=encoding, errors=errors, newline=newline
│    693 │   │   │   )
│    694 │   │   ) as read_file:

C:\Users\RAZIEL\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\osfs.py:640 in open

│   637 │   │   _mode = Mode(mode)
│   638 │   │   validate_open_mode(mode)
│   639 │   │   self.check()
│ > 640 │   │   _path = self.validatepath(path)
│   641 │   │   if _path == "/":
│   642 │   │   │   raise FileExpected(path)
│   643 │   │   sys_path = self._to_sys_path(_path)

C:\Users\RAZIEL\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\osfs.py:687 in  validatepath 
                                                                                  
│   684 │   │   │   │   msg="path '{path}' could not be encoded for the filesystem (check LANG" 
│   685 │   │   │   │   " env var); {error}".format(path=path, error=error),
│   686 │   │   │   )
│ > 687 │   │   return super(OSFS, self).validatepath(path)
│   688

C:\Users\RAZIEL\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\base.py:1577 in
│ validatepath                                                                                     │

│   1574 │   │   invalid_chars = typing.cast(six.text_type, meta.get("invalid_path_chars"))
│   1575 │   │   if invalid_chars:
│   1576 │   │   │   if set(path).intersection(invalid_chars):
│ > 1577 │   │   │   │   raise errors.InvalidCharsInPath(path)
│   1578 │   │
│   1579 │   │   max_sys_path_length = typing.cast(int, meta.get("max_sys_path_length", -1))
│   1580 │   │   if max_sys_path_length != -1: 

InvalidCharsInPath: path 'C:\Users\RAZIEL\AppData\Local\organize\organize\config.yaml' contains invalid characters

if I use `organize sim C:/Users/RAZIEL/AppData/Local/organize/organize/config.yaml` it works

**Comment by tfeldmann** [comment]
Update is released. Please update and try again!

**Comment by razielfayad** [comment]
> Update is released. Please update and try again!

problem solved, thanks.

**Comment by ktreharrison** [comment]
I am still getting the error 

Config: "C:\Users\haken\AppData\Local\organize\organize\config.yaml"
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│                                                                                                  │
│ C:\Users\haken\AppData\Local\Programs\Python\Python310\lib\site-packages\organize\cli.py:86 in   │
│ run_local                                                                                        │
│                                                                                                  │
│    83 │   try:                                                                                   │
│    84 │   │   console.info(config_path=config_path, working_dir=working_dir)                     │
│    85 │   │   config_dir, config_name = split(config_path)                                       │
│ >  86 │   │   config = open_fs(config_dir).readtext(config_name)                                 │
│    87 │   │   os.chdir(working_dir)                                                              │
│    88 │   │   core.run(rules=config, simulate=simulate)                                          │
│    89 │   except NeedsMigrationError as e:                                                       │
│ C:\Users\haken\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\base.py:691 in       │
│ readtext                                                                                         │
│                                                                                                  │
│    688 │   │                                                                                     │
│    689 │   │   """                                                                               │
│    690 │   │   with closing(                                                                     │
│ >  691 │   │   │   self.open(                                                                    │
│    692 │   │   │   │   path, mode="rt", encoding=encoding, errors=errors, newline=newline        │
│    693 │   │   │   )                                                                             │
│    694 │   │   ) as read_file:                                                                   │
│                                                                                                  │
│ C:\Users\haken\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\osfs.py:640 in open  │
│                                                                                                  │
│   637 │   │   _mode = Mode(mode)                                                                 │
│   638 │   │   validate_open_mode(mode)                                                           │
│   639 │   │   self.check()                                                                       │
│ > 640 │   │   _path = self.validatepath(path)                                                    │
│   641 │   │   if _path == "/":                                                                   │
│   642 │   │   │   raise FileExpected(path)                                                       │
│   643 │   │   sys_path = self._to_sys_path(_path)                                                │
│                                                                                                  │
│ C:\Users\haken\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\osfs.py:687 in       │
│ validatepath                                                                                     │
│                                                                                                  │
│   684 │   │   │   │   msg="path '{path}' could not be encoded for the filesystem (check LANG"    │
│   685 │   │   │   │   " env var); {error}".format(path=path, error=error),                       │
│   686 │   │   │   )                                                                              │
│ > 687 │   │   return super(OSFS, self).validatepath(path)                                        │
│   688                                                                                            │
│                                                                                                  │
│ C:\Users\haken\AppData\Local\Programs\Python\Python310\lib\site-packages\fs\base.py:1577 in      │
│ validatepath                                                                                     │
│                                                                                                  │
│   1574 │   │   invalid_chars = typing.cast(six.text_type, meta.get("invalid_path_chars"))        │
│   1575 │   │   if invalid_chars:                                                                 │
│   1576 │   │   │   if set(path).intersection(invalid_chars):                                     │
│ > 1577 │   │   │   │   raise errors.InvalidCharsInPath(path)                                     │
│   1578 │   │                                                                                     │
│   1579 │   │   max_sys_path_length = typing.cast(int, meta.get("max_sys_path_length", -1))       │
│   1580 │   │   if max_sys_path_length != -1:                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
InvalidCharsInPath: path 'C:\Users\haken\AppData\Local\organize\organize\config.yaml' contains invalid characters

**Comment by tfeldmann** [comment]
You are still running an old version. Use `organize --version` to check, it should be v2.1.2

**Comment by ktreharrison** [comment]
All good. Thanks again, love the tool ! 

Config: "C:\Users\haken\AppData\Local\organize\organize\config.yaml"

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SIMULATION                                                                                                                                                                                                                                                                                 │ 
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ 

⚙ Rule 1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
/C:\Users\haken\Downloads\
  Jan Milestone Chart.pdf
    - (echo) Ken
  The_Skills_Life_Cycle_for_Top_IT_Roles.pdf
    - (echo) Ken
  The_Skills_Life_Cycle_for_Top_IT_Roles_Part_2.pdf
    - (echo) Ken

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ 
│ SIMULATION                                                                                                                                                                                                                                                                                 │ 
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

success 3 / fail 0

**Comment by tfeldmann** [comment]
👍 Great to hear!
