### ISSUE TITLE
Initial setup fails on Windows with 'The system cannot find the path specified'

### ISSUE THREAD

**Issue by evenprimes** [tfeldmann/organize#185]
# Problem Statement
On a fresh install `organize edit` fails with 'The system cannot find the path specified'. The editor it attempted to open was notepad and it simply gave an untitled document that prompted for a save location.

# Attempt to resolve

Running `organize reveal` opens explorer with a generic window, not showing any actual folder. I was hoping this would at least reveal the path that was needed so I could manually create the folder without doing a dive into the code.

# System details

* `organize, version 2.0.9`
* `Python 3.10.2`
* Shell is Powershell 7.2.1
* Windows 10 (I think fully patched as of today)

**Comment by tfeldmann** [comment]
Update is released. Please update and try again!

**Comment by evenprimes** [comment]
> Do you have a env variable `ORGANIZE_CONFIG` set?

No



> What is the output of `organize reveal --path`?
C:\Users\didge\AppData\Local\organize\organize\config.yaml

I updated to the most recent version with the same errors, and `organize --version` reporting v2.1.2. However, now that I know about the `organize reveal --path` subcommand, I created the .\organize\organize directories and I got prompted to create the file.
