### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by wintuxx** [tfeldmann/organize#186]
Hello,
I have a little luxury problem.

I noticed that organize no longer writes anything to the logfile. 

What is the reason for this? In /.cache/organize/log/ there is the logfile organize.log but with 0 bytes.

**Comment by tfeldmann** [comment]
v2 was pretty much a rewrite and the logging output fell under the couch in the process. At the moment only exceptions are logged here. I'll slowly reintroduce it while working on the software 👍
