### ISSUE TITLE
organize sim not simulate rules sequentially considering outcomes of previous rules

### ISSUE THREAD

**Issue by iburunat** [tfeldmann/organize#189]
I noticed that when having two rules (the second one depending on the first), I notice that `organize sim` does not take into account the outcome of the first to simulate the second. 

For instance, if the first rule moves images to a folder `TEMP` and the second rule takes those images from `TEMP` and moves them elsewhere, `organize sim` will only simulate the outcome of the first rule (moving images to `TEMP`) but will ignore the second rule because it does not find any images in `TEMP` at the time of the simulation.

**Comment by tfeldmann** [comment]
Sorry for the late reply. Unfortunately simulating this correctly would be super complex without touching the filesystem.
So currently this is out of scope - if someone has a good idea how to do this, bring it on!
