### ISSUE TITLE
Organize docs opens 2.1.0 version instead of the latest one

### ISSUE THREAD

**Issue by elsatch** [tfeldmann/organize#190]
I have installed organize in a Windows computer using pip3. As I tried the `organize docs` command, a browser launched the DOCS_URL:  https://organize.readthedocs.io/en/v2.1.0/

I got a message notifying that there was a newer version of the documentation on the site. 

![brave_J6DyybZzb0](https://user-images.githubusercontent.com/653433/154051487-3e2c721f-de16-4c7a-8f48-8f1f3d03c647.png)

I checked the cli.py file and DOCS_URL is pointing to the correct URL: https://organize.readthedocs.io/

I assume that the redirection is happening at the readthedocs site, but I could not find the parameter on the .readthedocs.yml, mkdocs.yml or any  other files.

**Comment by elsatch** [comment]
I have explored a bit further and realized that the 'Edit on Github' button on the top right corner is also broken. It points to https://github.com/tfeldmann/organize/edit/master/docs/index.md and it should point to https://github.com/tfeldmann/organize/edit/main/docs/index.md

After searching about this issue, it seems like to need to use the Read The Docs API v3 to define the default branch for the docs. Extended discussion and solution here: https://github.com/readthedocs/readthedocs.org/issues/7327

**Comment by tfeldmann** [comment]
Thanks for reporting! I reset the default version to `latest` on readthedocs. This should be available in a few hours I hope.
I fixed the edit button by overriding `edit_uri` in the mkdocs config 👍
