### ISSUE TITLE
(move) ERROR! destination already exists

### ISSUE THREAD

**Issue by Ahmedazim7804** [tfeldmann/organize#193]
I am using organize on termux, i updated v2 today and was trying porting the config but i cannot get Move action to overwrite files.

Sorry for poor code formatting.

My config:
`rules:`
`# Download Apps`
` - locations: /sdcard/Download/`
`      subfolders: false`
`      filters:`
`          - extension:`
`             - apk`
`              - apks`
`              - apkm`
`              - xapk`
`      actions:`
`          - move:`
`              dest: /sdcard/Download/Apps/`
`              on_conflict: "overwrite"`

The Error
`/sdcard/Download`
  `MacroDroidHelper_v1_7.apk`
    `- (move) MacroDroidHelper_v1_7.apk in
"/sdcard/Download/Apps" already exists!
(conflict mode is "overwrite").`
    `- (move) Overwrite
/sdcard/Download/Apps/MacroDroidHelper_v1_7.apk.`
    `- (move) Move to
/sdcard/Download/Apps/MacroDroidHelper_v1_7.apk`
    `- (move) ERROR! destination
'/Apps/MacroDroidHelper_v1_7.apk' exists`

Full Output:

`organize 2.1.2
Config: "/data/data/com.termux/files/home/.config/organize/config.yaml"

⚙ Rule 1 ───────────────────────────────────────
/sdcard/Download
  MacroDroidHelper_v1_7.apk
    - (move) MacroDroidHelper_v1_7.apk in
"/sdcard/Download/Apps" already exists!
(conflict mode is "overwrite").
    - (move) Overwrite
/sdcard/Download/Apps/MacroDroidHelper_v1_7.apk.
    - (move) Move to
/sdcard/Download/Apps/MacroDroidHelper_v1_7.apk
    - (move) ERROR! destination
'/Apps/MacroDroidHelper_v1_7.apk' exists

success 0 / fail 1
╭───── Traceback (most recent call last) ──────╮
│                                              │
│ /data/data/com.termux/files/usr/lib/python3. │
│ 10/site-packages/organize/cli.py:90 in       │
│ run_local                                    │
│                                              │
│    87 │   │   console.info(config_path=confi │
│    88 │   │   config = config_path.read_text │
│    89 │   │   os.chdir(working_dir)          │
│ ❱  90 │   │   core.run(rules=config, simulat │
│    91 │   except NeedsMigrationError as e:   │
│    92 │   │   console.error(e, title="Config │
│    93 │   │   console.warn(                  │
│ /data/data/com.termux/files/usr/lib/python3. │
│ 10/site-packages/organize/core.py:329 in run │
│                                              │
│   326 │   console.summary(count)             │
│   327 │                                      │
│   328 │   if count["fail"]:                  │
│ ❱ 329 │   │   raise RuntimeWarning("Some act │
│   330                                        │
╰──────────────────────────────────────────────╯
RuntimeWarning: Some actions failed.`

**Comment by Ahmedazim7804** [comment]
ScreenShots

![Screenshot_2022-02-18-18-48-55-72_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/54241827/154690139-b8d653d6-3488-4b92-bec4-4ad828d30015.jpg)

![Screenshot_2022-02-18-18-48-47-86_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/54241827/154690156-196e3dfc-d2fb-4a30-a5b0-96a74852a7b2.jpg)

**Comment by tfeldmann** [comment]
Can you try with the current development versio? E.g. `pip3 install https://git+github.com/tfeldmann/organize.git`

**Comment by Ahmedazim7804** [comment]
Yes, it works now with latest version.
thank you

**Comment by tfeldmann** [comment]
Thanks for the fast feedback!
