### ISSUE TITLE
Add ability to re-organize over smb/sFTP

### ISSUE THREAD

**Issue by eli-goldberg-ch** [tfeldmann/organize#195]
## What is it
Add protocol support to run organize over network drive locations, e.g., by `smb`. 

When I try to do this, I get a completely sensical and well articulated error: 

``` bash

ValueError: Invalid location smb://nasname._smb._tcp.local/Public/username (protocol
'smb' is not supported)

```

## Why is it important?
I want to re-organize my files on my NAS. The NAS itself supports SSH'ing in and supports a _version_ of python, but it would be awesome to be able to extend `organize` to be able to include the `smb` protocol explicitly.

**Comment by tfeldmann** [comment]
In order to use the smb protocol you need to install fs.smbfs:

https://pypi.org/project/fs.smbfs/

Then you can use a connection string (FS URL) like the given example to connect via smb.
