### ISSUE TITLE
How do i run this on Windows?

### ISSUE THREAD

**Issue by Teeyawn** [tfeldmann/organize#211]
pip install -U organize-tool

```
C:\Users\teonm\Desktop\Coding\organize>**py organize**
Traceback (most recent call last):
  File "C:\Users\teonm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\teonm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\teonm\Desktop\Coding\organize\organize\__main__.py", line 2, in <module>
    import cli
  File "C:\Users\teonm\Desktop\Coding\organize\organize\cli.py", line 11, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

I changed from .cli import cli in main py because i was getting the same error. Ive tried to PIP install click but thats not the solution either it seems?

```
C:\Users\teonm\Desktop\Coding\organize>pip install click
Requirement already satisfied: click in c:\users\teonm\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (8.1.2)
Requirement already satisfied: colorama in c:\users\teonm\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from click) (0.4.4)
```

Anyone have guidance? thanks again!

**Comment by xdhmoore** [comment]
I've been running it on windows ok. I think I installed with something like `pip install "organize-tool[textract]"` into a virtualenv.

**Comment by xdhmoore** [comment]
Are you trying to run from source? You mention the pip install command, but your stack trace looks like you have downloaded the `organize` code to your desktop and are running with the windows `py` launcher, which I'm not familiar with.

If you are just trying to run it and not necessarily from source, I installed with pip, and can now run `organize` as a command. It is on my path when the virtual env I installed it to is activated.

**Comment by tfeldmann** [comment]
This is an installation issue. To be safe you can use:

```
pip uninstall organize-tool
python3 -m pip install organize-tool
python3 -m organize-tool
```

But normally you should be able to run `organize` directly after installation.
I'll close this for now, please reopen if this issue persists!
