### ISSUE TITLE
Global exclusion rules and more?

### ISSUE THREAD

**Issue by zany130** [tfeldmann/organize#219]
**Is your feature request related to a problem? Please describe.**
I am always setting the same exclusions for all my rules which can be anyoning if I have several rules for example to workaround this https://github.com/tfeldmann/organize/issues/202

**Describe the solution you'd like**
Ability to add maybe to the top of the list some global rules

**Comment by tfeldmann** [comment]
I hope I understand this correctly - could you post an example? Have you looked into the alias functionality?
https://organize.readthedocs.io/en/latest/rules/#advanced-aliases

**Comment by zany130** [comment]
thats basicly what I was looking for lol sorry. here how i implemented it to my config and it seems to work https://dpaste.com/2M6UAXV3A
