### ISSUE TITLE
exif filters

### ISSUE THREAD

**Issue by mope1** [tfeldmann/organize#22]
having a filter type to access exif metadata fields would be very useful for photos and images

https://en.wikipedia.org/wiki/Exif

**Comment by mope1** [comment]
https://github.com/tfeldmann/organize/issues/22

https://github.com/tfeldmann/organize/blob/master/todo.md

started work here https://github.com/mope1/organize/blob/f22-exif-filters/organize/filters/exif.py

**Comment by tfeldmann** [comment]
I just released version 1.7.0 which includes an exif filter 🎉

**Comment by tutume** [comment]
Hello,

recently I found your project and it is very interesting, easy and helpful. Thanks for your work and congratulations.

I'm playing with it to help me organize my file in general. Many images, videos and docs also. Regarding exif filter and metadata in general, the exifread library that you are using if very limited and it cannot even find some exif in some of my regular media files (originals from iphones, androids and DSLR cameras). I already know and use [exiftool](https://exiftool.org/). This tool is amazing and actually is much more then "exif" tool, it is capable to read and write many metadata formats. There is a [pyexiftool](https://github.com/smarnach/pyexiftool) wrapper.
I have [created](https://gist.github.com/tutume/f2fa1f2f94e008c3288b0bb005c1ccfc) and tested a little a basic copy/past/refactor from your exif plugin and it works. 

Would consider validate my "crappy" work and add it to your tool?

**Comment by iburunat** [comment]
That would be an excellent addition. I extensively use EXIF mostly for extracting original date info and sort in date subfolders. I basically use shell in such cases:

```yaml
       - shell: |
          magick "{path}" -resize '1440x1440>' "{path.parent}/{path.stem}_r.jpg"
          exiftool -tagsFromFile "{path}" "{path.parent}/{path.stem}_r.jpg"
          exiftool '-FileCreateDate<DateTimeOriginal' "{path.parent}/{path.stem}_r.jpg"
          mv "{path.parent}/{path.stem}_r.jpg_original" ~/.Trash
```

This would resize and copy all metadata to the resized media with EXIF. Not sure if there is a more efficient way to do this at this point.
