### ISSUE TITLE
running organize gets "can't import cli" error

### ISSUE THREAD

**Issue by Chefback** [tfeldmann/organize#222]
**Describe the bug**
I try to run the newest version organize  ,but get the following error
>Traceback (most recent call last):
  File "/usr/bin/organize", line 5, in <module>
    from organize.cli import cli
ImportError: cannot import name 'cli' from 'organize.cli' (/home/lin/.local/lib/python3.10/site-packages/organize/cli.py)

however when i add sudo, it can work
**Expected behavior**

**Screenshots**
![2022-06-12_22-44.png](https://s2.loli.net/2022/06/12/xMT3J2FN9wEvi4h.png)
**Environment (please complete the following information):**
 - OS:![2022-06-12_22-41.png](https://s2.loli.net/2022/06/12/tpQm1xz8bnhW5k9.png)
 - Output of `organize --version`: 

**Your config file**
just the default config,I removed the old one and installed the v2 version

**Comment by tfeldmann** [comment]
This is an installation issue and a bit difficult to troubleshoot. You might have multiple versions of organize installed. Did you install with sudo? Can you try a complete reinstall?

**Comment by tfeldmann** [comment]
Closing the issue, I hope everything works now!
