### ISSUE TITLE
Windows configfile encoding

### ISSUE THREAD

**Issue by random623** [tfeldmann/organize#224]
Not sure if bug. Just updated to V2 and now I have a problem with the encoding. With config file encoding UTF8 I get problems in the path and there is a / before the filename:

> (move) Move to C:\ErtragsausschÃ¼ttung\/ERTRAGSGUTSCHRIFT.pdf

When I change the config file encoding to ANSI it seems to work.

> (move) Move to C:\Ertragsausschüttung\ERTRAGSGUTSCHRIFT.pdf

```
 rules:   
   - locations: D:\Downloads\
     #sublocationss: false
     filters:
       - extension:
           - pdf
       - name:
           startswith : "Ertragsgutschrift"
           contains : "2022"
           case_sensitive: false
     actions:
       - move: C:\Ertragsausschüttung\
```

Is that how it's meant to be? I thought UTF8 should be the correct encoding.

Windows 10, organzie 2.2.0, python 3.9.0

**Comment by tfeldmann** [comment]
Can you send me the config file via mail?

**Comment by random623** [comment]
I just updated to an new system with Windows 11 and did an clean install. UTF8 is now working as expected. Not sure what caused that behavoiur. On the new system I had to convert my configs back to UTF8.
