### ISSUE TITLE
Add filter: Date Last Opened

### ISSUE THREAD

**Issue by ARtHryDr** [tfeldmann/organize#225]
**Is your feature request related to a problem? Please describe.**
 Files are not always modified, but often only accessed, so the `lastmodified` filter is not always useful, at least on macOS.

**Describe the solution you'd like**
Add the option to filter by the date of last access to the file.

**Additional context**
I don't know how it should be implemented on other operating systems, but I think that on macOS, copying the implementation of 83ed1f848fe0a8c8560c80d36313b0c669f64549 with the `kMDItemLastUsedDate` parameter of the `mdls` command would be enough.

**Comment by tfeldmann** [comment]
This is incuded in the next release.
