### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by frediz** [tfeldmann/organize#230]
Hi,
I package organize for Debian and with organize 1.10, I was able to produce a man page by going into the docs directory and running "make man".
With organize 2.2 and  mkdocs, it does not seem possible.
Do you plan to have a man page ? it would be nice as Debian packages are required to have one.
Thanks a lot for the great tool,
Fred

**Comment by tfeldmann** [comment]
Hey thanks a lot for packaging!

You should be able to generate manpages by pulling the latest version from main branch (just fixed this) and running

```
poetry install
poetry run click-man organize
```

Could you check if that works for you?

**Comment by frediz** [comment]
I'm not familiar with poetry, but I see this would be using a virtualenv and that is not
what the packaging in Debian is using (rather using system installed python libraries).
So at the moment, I'm not able to answer you, but there's no reason I can't reproduce this at the system level.
I'm going to play a bit with that and will come back to you.
Thanks for showing a path, I was clueless.
F.

**Comment by tfeldmann** [comment]
This is meant only as a way to generate the man pages. For packaging organize no virtualenv should be needed, it's just recommended for the dev dependencies. But I have no clue about packaging for debian, so maybe I'm missing something 😅

**Comment by frediz** [comment]
Hi Thomas,
poetry actually pulls a whole virtualenv to be able to run but while a package is being
built in Debian, it shouldn't try to fetch online stuff (you have to rely on the distro libs only).
Anyway, Debian packages click-man 0.4.1 at the moment from https://github.com/click-contrib/click-man/ .
Playing with PYTHONPATH to point to locally built "organize", I'm able to run : ```click-man organize`` in the build tree`.
But it fails in the middle of click-man and it's because of ```hidden=True``` that is not supported by the click-man from Debian and I see you actually point to a fork's branch that has support for that.
So for now, I may just patch ```cli.py``` which then enables upstream click-man to generate all the manpages :) :+1:

**Comment by tfeldmann** [comment]
Yes I ran into that bug, too! Just removing the hidden options is a good workaround. Thanks for the update, great work 👍

**Comment by frediz** [comment]
I think we can close this one !
F.
