### ISSUE TITLE
exif data can't be read on M1 osx laptops

### ISSUE THREAD

**Issue by jleatham** [tfeldmann/organize#267]
**Describe the bug**
When reading exif data, the system throws an error:
```
    actions:
      - echo: "datetime: {exif.image.datetime}"
```

output:
not useful error:
```
  IMG_4756.HEIC 
    - (exif) ERROR! hdlr
```

Solution found in random thread: https://github.com/ianare/exif-py/issues/160

```
pip install "exifread<3" solved this for me.

I'm on macOS (Apple silicon).
```

This allowed exif to start working properly.

organize, version 2.4.0
osx : 12.6.1, M1 Mac apple silicon

**Comment by tfeldmann** [comment]
I can reproduce this for HEIC images. I'm submitting an update to fix this.
