### ISSUE TITLE
not reading exif data from cr3 files

### ISSUE THREAD

**Issue by SeeThruHead** [tfeldmann/organize#278]
**Is your feature request related to a problem? Please describe.**
i would like to organize my photos by camera model and date taken
but organize is unable to read exif data from cr3 files (not sure about other photo extensions)

**Describe the solution you'd like**
should read exif data from all photo types

**Describe alternatives you've considered**
could use created at date, and assume cr3 files are generated by a single camera model (not accurate)

**Comment by tfeldmann** [comment]
Hi, thanks for reporting! I found cr3 is neither supported by `pillow` nor by `exifread`. It would be great if we could use something like Phil Harvey's [exiftool](https://exiftool.org).

**Comment by tfeldmann** [comment]
I just released v3 with `exiftool` support. Install the tool from exiftool.org and set an environment variable `ORGANIZE_EXIFTOOL_PATH="exiftool"` pointing to the executable. Then organize uses exiftool under the hood and supports nearly all the image formats 🚀
