### ISSUE TITLE
Message text is unreadable with a white terminal

### ISSUE THREAD

**Issue by elskewe** [tfeldmann/organize#312]
**Describe the bug**
Messages are printed in white and are thus unreadable when using a terminal with a white theme (e.g. the default command line of Windows 11).

**Screenshots**
Default:
![image](https://github.com/tfeldmann/organize/assets/19361925/df0439c1-43d4-4128-824e-f3def51674b9)

Changing 
https://github.com/tfeldmann/organize/blob/10ca44fb360df4041d09bd88aaa723291be07898/organize/console.py#L36

to 
````
 "pipeline.msg": "black", 
````
gives this output with the messages readable:
![image](https://github.com/tfeldmann/organize/assets/19361925/2a8a9130-f9ad-4262-bddb-a5b2346f38d9)

**Environment (please complete the following information):**

- OS: Windows 11
- Output of `organize --version`: organize, version 2.4.2

**Your config file**

```yaml
# paste your config file here
```

**Comment by tfeldmann** [comment]
This should be fixed in the new version 👍
