### ISSUE TITLE
V3 Windows 11 config file encoding

### ISSUE THREAD

**Issue by random623** [tfeldmann/organize#335]
**Describe the bug**
Just did an update to v3.0.0a0 on Windows 11. With V2 the config file was saved as UTF-8 and Umlaute worked fine. After updating to V3 Umlaute in paths were wrong, example "ErtrÃ¤ge" instead "Erträge". Changing the config encoding to Windows 1252 fixed the issue. Not sure if bug or desired behaviour.

**Comment by tfeldmann** [comment]
Hi thanks for testing and reporting! TIL python3 is not UTF-8 by default on windows.
I'll release a fix in a few minutes. You might want to set the `PYTHONUTF8=1` environment variable in the meantime!

**Comment by tfeldmann** [comment]
V3.0.0a1 is released

**Comment by tfeldmann** [comment]
I just released v3. This should be fixed. Please reach out if it is not working!
