### ISSUE TITLE
LastModified gives always an error

### ISSUE THREAD

**Issue by MAWSpitau** [tfeldmann/organize#35]
Hi there, 

this is my rule:

```
- folders:
    - ~/Dropbox/neuesortierung/lecturenotes
    filters:
      - Extension:
        - pdf
        - PDF
      - LastModified:
        - days: 10
    actions:
      - Shell: shrinkpdf "{path}"
```

Running `organize sim` or `run` gives me this output:

```
ERROR! unsupported type for timedelta days component: dict
Full traceback at: /home/marcel/.cache/organize/log/organize.log
```

full traceback:

```
2019-06-05 08:51:51,976 - organize.main - ERROR - unsupported type for timedelta days component: dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/organize/main.py", line 102, in main
    execute_rules(config.rules, simulate=args['sim'])
  File "/usr/local/lib/python3.6/dist-packages/organize/config.py", line 134, in rules
    rule_filters = list(self.instantiate_filters(rule_item))
  File "/usr/local/lib/python3.6/dist-packages/organize/config.py", line 95, in instantiate_filters
    yield self._class_instance_with_args(filter_class, args)
  File "/usr/local/lib/python3.6/dist-packages/organize/config.py", line 71, in _class_instance_with_args
    return Cls(*args)
  File "/usr/local/lib/python3.6/dist-packages/organize/filters/last_modified.py", line 83, in __init__
    days=days, hours=hours, minutes=minutes, seconds=seconds)
TypeError: unsupported type for timedelta days component: dict
```

I have no idea what I am doing wrong, or what is wrong with my system or my config.

I would appreciate some help.

Marcel

**Comment by tfeldmann** [comment]
Hi Marcel,

in YAML a dash indicates an array / list:
```
- LastModified:
    - days: 10
```

but the LastModified filter accepts only dicts as parameters:

```
- LastModified:
    days: 10
```

So your correct rule would be:

```
  - folders:
    - ~/Dropbox/neuesortierung/lecturenotes
    filters:
      - Extension:
        - pdf
        - PDF
      - LastModified:
        days: 10
    actions:
      - Shell: shrinkpdf "{path}"
```

Thomas

**Comment by MAWSpitau** [comment]
Thanks a lot! That seems to look better. At least do not get an error-message. 

BUT I just used the documentation on:  https://organize.readthedocs.io/en/latest/page/filters.html#lastmodified

And there it **is** indicated with an dash! 

![grafik](https://user-images.githubusercontent.com/539371/58940210-361a5a00-8779-11e9-97fd-2ecd8507dc2e.png)

On the other hand it is not working in a proper way. 

this is my config:

```
# LectureNotes shrinken
  - folders:
    - ~/Dropbox/neuesortierung/lecturenotes
    filters:
     - LastModified:
        hours: 1     
     - Extension:
        - pdf
        - PDF
    actions:
      - Echo: "{lastmodified.year}/{lastmodified.month}/{lastmodified.day} - {lastmodified.hour}:{lastmodified.minute} "
```
But I get all pdfs in that dir... 
![grafik](https://user-images.githubusercontent.com/539371/58940836-d91fa380-877a-11e9-9e47-e292926f8eaf.png)

One more hint, and I would be very happy. 

Thanks
Marcel

**Comment by tfeldmann** [comment]
> And there it is indicated with an dash!
Oops! That's an error, thank you for reporting! I just changed it.

Your config looks fine now. LastModified has a mode setting - if you want to filter files modified within the last hour you need to set `mode: 'newer'`:

```
rules:
  - folders:
      - ~/Dropbox/neuesortierung/lecturenotes
    filters:
      - LastModified:
          hours: 1
          mode: newer
      - Extension: pdf
    actions:
      - Echo: "{lastmodified.year}/{lastmodified.month}/{lastmodified.day} - {lastmodified.hour}:{lastmodified.minute} "
```
(Note that the Extension filter is case insensitive)

Hope it works now!

**Comment by MAWSpitau** [comment]
That's it! Thanks a lot!
