### ISSUE TITLE
rename action error: ERROR! Missing value for template: 'builtin_function_or_method object' has no attribute  'strftime'

### ISSUE THREAD

**Issue by davebooi** [tfeldmann/organize#357]
**Describe the bug**
rename action in conjunction with placeholder variable {now}  is not renaming files properly.
Output file name is incorrect and placeholder {now} not pulled in properly.

Example input PDF: Testfile.pdf
filename after rename & move: Testfile_<built-in method now of type object at 0x7f6f2abbe820>.pdf

**Screenshots**
![swappy-20240222-143816](https://github.com/tfeldmann/organize/assets/25366836/1c8b163c-9bcb-49b1-b3c3-50b5853a4d26)

**Environment (please complete the following information):**

- OS: Linux Fedora 39, Python 3.12.1
- Output of `organize --version`:  organize v3.2.0

```yaml
# paste your config file here
`# organize configuration file
# https://organize.readthedocs.io


rules:
# PDF
  - name: "move PDFs"
    locations:
      - ~/Downloads/
    subfolders: false
    filters:
      - extension:
        - pdf
      - hash
      - name
    actions:
      - echo: "found {extension}: {name}"
      - rename: "{name}_{now}.{extension}"
      - move: 
            dest: "~/Downloads/pdf/"
            on_conflict: "rename_new"
            rename_template: "{name}__{now} {extension}"`

**Comment by tfeldmann** [comment]
This is a documentation issue, thanks for reporting! Please try again with `{now()}`.

**Comment by tfeldmann** [comment]
Yep, just updated the docs!
