### ISSUE TITLE
Error: Config problem

### ISSUE THREAD

**Issue by rxng** [tfeldmann/organize#359]
**Describe the bug**
After installing organize-tool with no errors and running the command in the README

```
pip install -U organize-tool 
organize new
```
the following error is encountered

```
Error: Config problem
Cannot find config "/home/user/.config/organize/config.yaml"
```

Was the folder and config file supposed to have been created automatically but something went wrong?

**Environment (please complete the following information):**

- OS: Opensuse tumbleweed
- Output of `organize --version`: organize v3.2.1

**Your config file**

```yaml
# paste your config file here
```

**Comment by jakebiller19** [comment]
Getting same error on Windows-- tried manually creating config.yaml, still does not work

**Comment by x61** [comment]
Same error message on MacOS

**Comment by tfeldmann** [comment]
Thanks everyone for the reports! Will be fixed in the next version.

**Comment by tfeldmann** [comment]
Update is released 👍
