### ISSUE TITLE
return {lastmodified.month} with leading zero

### ISSUE THREAD

**Issue by davethehacker** [tfeldmann/organize#37]
could there be an option, to get the month value with a leading zero? I want to rename my files an make them sortable by date/month

**Comment by tfeldmann** [comment]
It's already there - you can use everything the `.format()` function offers. For months with leading zeros you can use:
```{lastmodified.month:02}```

(https://docs.python.org/3/library/string.html#formatspec)

**Comment by davethehacker** [comment]
Thanks. I did not know about this. Is it documented?
