### ISSUE TITLE
XDG_CONFIG_HOME ignored by default on macOS

### ISSUE THREAD

**Issue by gfontenot** [tfeldmann/organize#371]
**Describe the bug**
Despite having support for `XDG_CONFIG_HOME` in actions like `organize list` (as well as having support for finding configs in that location via `find_config`), the only way to use a config in that location is to explicitly set the `ORGANIZER_CONFIG` environment variable. It feels silly to have support built into the tool for this convention without supporting it for the most important use case. 

**Screenshots**
```
❯ organize show
Error: Config problem
Cannot find config "/Users/fontenot/Library/Application Support/organize/config.yaml".
❯ organize list
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Config ┃ Path                                         ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ config │ /Users/fontenot/.config/organize/config.yaml │
└────────┴──────────────────────────────────────────────┘
```

**Environment (please complete the following information):**

- OS: macOS 14.3
- Output of `organize --version`: organize v3.2.2

**Comment by tfeldmann** [comment]
Thanks a lot for reporting. Yes this is silly and will be fixed in the next release 👍

**Comment by gfontenot** [comment]
Thanks for the quick turnaround on this!
