### ISSUE TITLE
macos_tags problem

### ISSUE THREAD

**Issue by bluedogtwo** [tfeldmann/organize#376]
**Describe the bug**
When using the filter macos_tags I get an error. - (macos_tags) ERROR! No module named 'macos_tags'. I can see the file exists /opt/homebrew/Cellar/organize-tool/3.2.3/libexec/lib/python3.12/site-packages/organize/filters/macos_tags.py.

**Screenshots**

**Environment (please complete the following information):**

- OS: macOS Sonoma
- Output of `organize --version`:
organize v3.2.3

**Your config file**

```yaml
 filters:
      - macos_tags: "* (red)"
```

**Comment by tfeldmann** [comment]
It seems like the `macos_tags` library is missing on your system. Can you try running `python3 -m pip install macos_tags`?

**Comment by tfeldmann** [comment]
I just checked the homebrew formula, which seems to be correct. I'm confused about how this could happen. Any idea?

**Comment by bluedogtwo** [comment]
is this helpful?
brew ls organize-tool
/opt/homebrew/Cellar/organize-tool/3.2.3/bin/organize
/opt/homebrew/Cellar/organize-tool/3.2.3/libexec/bin/ (14 files)
/opt/homebrew/Cellar/organize-tool/3.2.3/libexec/lib/ (1398 files)
/opt/homebrew/Cellar/organize-tool/3.2.3/libexec/pyvenv.cfg

**Comment by tfeldmann** [comment]
I've looked into this some more and it seems like the homebrew formula is indeed missing the macos-tags dependency.
I opened the upstream PR here: https://github.com/Homebrew/homebrew-core/pull/168089

Thanks for reporting!

**Comment by tfeldmann** [comment]
The people over at homebrew are really fast. This should be fixed now, you might need to `brew update` and `brew reinstall organize-tool`.
