### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by nothing2obvi** [tfeldmann/organize#386]
**Is your feature request related to a problem? Please describe.**
Organize is really great. I use it now. However, I just switched from Hazel and the only thing that seems to be missing for me is the file-renaming in Hazel -- for now, I'm really just looking for 2 options, to remove text and to replace text within a filename.

**Describe the solution you'd like**
More options in the `rename` action that allow you to replace or remove certain strings from the filename or add variables. See `Additional context` below.

**Describe alternatives you've considered**
I have tried through trial and error for a few hours now to Google for help and run a simple script that will remove a string from a filename, but I can't get it to work. I am a total beginner at scripting. I have also tried to install the `rename` command with no success, as it won't persist. I've now switched to FileFlows just for the renaming task.

**Additional context**
https://www.noodlesoft.com/manual/hazel/attributes-actions/action-reference/using-patterns-in-actions/

**Comment by tfeldmann** [comment]
In organize you have a **lot** of options on how to replace text or removing strings from a file name. You can use regular expressions, python scripts or build a name from template variables.

The easiest option might be this:

```yaml
rules:
  - name: "Germanize"
    locations: "/test"
    actions:
    - rename: "{path.name.replace('file', 'Datei')}"
```

**Comment by nothing2obvi** [comment]
Hmm, okay. I guess I have bit more exploring to do in Organize. Thanks! Might need to continue this thread or ask elsewhere if I come up with questions.

**Comment by tfeldmann** [comment]
Please feel free to post your questions, these are great starting points for improving the docs :)

**Comment by nothing2obvi** [comment]
Okay, thanks! I spun up FileFlows to accomplish this but if I could remove that service from my system and just stick to Organize I would prefer that.

1.) How do you remove the string "1234" from a filename? So "File1234" or "1234File" becomes "File"?

2.) How do you replace the string "1234" with "5678"? So "File1234" or "1234File" becomes "File5678" or "5678File", respectively?

Just those simple questions for now. I appreciate your help!

**Comment by nothing2obvi** [comment]
I figured it out using your `path.name.replace` example. Thank you! I'd like to suggest adding it to the docs, as I searched for it and couldn't find it.
