### ISSUE TITLE
Globstrings on folders don't work (anymore)

### ISSUE THREAD

**Issue by kpprt** [tfeldmann/organize#39]
I updated to version 1.5 and I'm getting the following error:
ERROR! Path does not exist: ~/Downloads/*.pdf

Config is:
- folders: '~/Downloads/*.pdf'

Seems like globstrings don't work anymore in folders.

**Comment by tfeldmann** [comment]
Yep this is a bug. Should be fixed in the next version. I added an integration test to prevent regressions in the future. Thank you for reporting!

**Comment by kpprt** [comment]
Thank you for fixing!

**Comment by tfeldmann** [comment]
New version is just released 👍
