### ISSUE TITLE
Help installing in Linux Mint virtual python env

### ISSUE THREAD

**Issue by feather42** [tfeldmann/organize#394]
**Describe the bug**
I am not good with python sorry I will try to articulate my issue clearly and appreciate any help.

I have used organize (v2) for years but I had to rebuild my machine (Linux mint debian edition) when I came to install organize I get all sorts of messages about python now using virtual environments which isn't covered in the organize installation instructions. 

I have followed the directions the OS gives and have got organize installed but when I test it by running 
organize --help
I get error messages about
File "/home/auser/.local/pipx/venvs/organize-tool/lib/python3.11/site-packages/pydantic/dataclasses.py", line 196, in create_dataclass
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Cannot create a Pydantic dataclass from Location as it is already a Pydantic model

and I am now at a loss how to resolve this, its beyond my capabilities and googling it doesn't help, what little information I find I can't understand.

Please can anybody help?

**Environment (please complete the following information):**
- OS: Linux Mint 6.1.0-22-amd64

- Output of `organize --version`:
- organize wont run but its a fresh install so should be the latest version

**Your config file**
I haven't yet created a v3 config file as I cant get organize to run

**Comment by elispapa2010** [comment]
Same issue. 

Kernel: 5.15.0-113-generic x86_64 bits: 64
    compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33 wm: muffin
    vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy


Output of organize new:

Traceback (most recent call last):
  File "/usr/bin/organize", line 7, in <module>
    main()
  File "/usr/lib/python3/dist-packages/organize/cli.py", line 47, in main
    args = docopt(__doc__, argv=argv, version=__version__, help=True)
TypeError: docopt() got an unexpected keyword argument 'help'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_organize.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/organize", line 7, in <module>
    main()
  File "/usr/lib/python3/dist-packages/organize/cli.py", line 47, in main
    args = docopt(__doc__, argv=argv, version=__version__, help=True)
TypeError: docopt() got an unexpected keyword argument 'help'

**Comment by tfeldmann** [comment]
Hi, thanks for reporting! How did you install organize? Did you try to install using pipx?
Can you post the output of pip list?

**Comment by feather42** [comment]
Thanks for the response.
I did a fresh install of LMDE on a Dell XPS13, I installed my standard apps then I came to install organize and tried the install command as per the docs pip install -U organize-tool this failed I got messages about the new way python works with virtual env so I followed the instructions and did:
sudo apt install pipx
pipx install -U organize-tool  <<this didn't work then I found to omit the -U
pipx install organize-tool <<this worked and installed organize
pipx ensurepath <<this was recommended by the OS without it organize wouldnt run at all
reboot
organize --help <<this generated the error message

As requested here is pip list output
Package            Version
------------------ ------------
anyio              3.6.2
apt-clone          0.2.1
apturl             0.5.2
argcomplete        2.0.0
attrs              22.2.0
Babel              2.10.3
beautifulsoup4     4.11.2
Brlapi             0.8.4
Brotli             1.0.9
certifi            2022.9.24
chardet            5.1.0
charset-normalizer 3.0.1
click              8.1.3
colorama           0.4.6
configobj          5.0.8
cryptography       38.0.4
cupshelpers        1.0
dbus-python        1.3.2
defer              1.0.6
deprecation        2.0.7
distro             1.8.0
dnspython          2.3.0
eyed3              0.9.7
filelock           3.9.0
filetype           1.2.0
ghp-import         2.1.0
grpcio             1.51.1
h11                0.14.0
h2                 4.1.0
hpack              4.0.0
html5lib           1.1
httpcore           0.16.3
httplib2           0.20.4
httpx              0.23.3
hyperframe         6.0.0
idna               3.3
ifaddr             0.1.7
IMDbPY             2021.4.18
iniconfig          1.1.1
Jinja2             3.1.2
joblib             1.2.0
libevdev           0.5
livereload         2.6.3
louis              3.24.0
lunr               0.6.2
lxml               4.9.2
Mako               1.2.4.dev0
Markdown           3.4.1
markdown-it-py     2.1.0
MarkupSafe         2.1.2
mdurl              0.1.2
mergedeep          1.3.4
mkdocs             1.4.2
more-itertools     8.10.0
mutagen            1.46.0
nemo-emblems       6.0.1
netaddr            0.8.0
netifaces          0.11.0
nltk               3.8
numpy              1.24.2
onboard            1.4.1
packaging          23.0
PAM                0.4.2
pexpect            4.8.0
Pillow             9.4.0
pip                23.0.1
pipx               1.1.0
pluggy             1.0.0+repack
protobuf           4.21.12
psutil             5.9.4
ptyprocess         0.7.0
py                 1.11.0
pycairo            1.20.1
pycryptodomex      3.11.0
pycups             2.0.1
pycurl             7.45.2
pydantic           1.10.4
pyelftools         0.29
Pygments           2.14.0
PyGObject          3.42.2
pyinotify          0.9.6
PyNaCl             1.5.0
pyparsing          3.0.9
pyparted           3.12.0
pypng              0.20220715.0
pytest             7.2.1
python-apt         2.6.0
python-dateutil    2.8.2
python-debian      0.1.49
python-gnupg       0.4.9
python-magic       0.4.26
python-xlib        0.33
pytz               2022.7.1
pyudev             0.24.0
pyxdg              0.28
PyYAML             6.0
pyyaml_env_tag     0.1
qrcode             7.4.2
regex              2022.10.31
reportlab          3.6.12
requests           2.28.1
requests-file      1.5.1
requests-toolbelt  0.10.1
rfc3986            1.5.0
rich               13.3.1
setproctitle       1.3.1
setuptools         66.1.1
simplejson         3.18.3
six                1.16.0
sniffio            1.2.0
soupsieve          2.3.2
systemd-python     235
tinycss2           1.2.1
tldextract         3.1.2
tornado            6.2
tqdm               4.64.1
typing_extensions  4.4.0
ufw                0.36.2
Unidecode          1.3.6
urllib3            1.26.12
userpath           1.8.0
variety            0.8.10
watchdog           2.2.1
webencodings       0.5.1
websockets         10.4
wheel              0.38.4
xdg                5
xlrd               1.2.0
yt-dlp             2023.7.6

I also did pipx list and this is the output
pipx list
venvs are in /home/auser/.local/pipx/venvs
apps are exposed on your $PATH at /home/auser/.local/bin
   package organize-tool 3.2.3, installed using Python 3.11.2
    - organize

Thanks for any help you can give to get this working.

**Comment by tfeldmann** [comment]
Thanks! Can you post the output of `which organize`? Pipx list is looking fine, might be a PATH issue.

**Comment by feather42** [comment]
Thanks, which organize gives this output
/home/auser/.local/bin/organize

and $PATH gives this output
bash: /home/auser/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin:/home/auser/.local/bin:/home/auser/.local/bin: No such file or directory

**Comment by tfeldmann** [comment]
Ok, I've looked into this a bit and it seems like there's a bug which is not swallowed anymore with the latest dependencies. So thanks again for reporting, there's nothing wrong with your setup but you found a bug in organize.
I will push a fix as soon as possible!

**Comment by tfeldmann** [comment]
@elispapa2010

Is it possible you are still on Version 1.x? Please try installing the new version :)

**Comment by feather42** [comment]
Thanks for taking a look so quickly good to hear my install looks ok, I look forwards to the update.

**Comment by tfeldmann** [comment]
New version 3.2.4 is out, can you retry?

**Comment by nblock** [comment]
> New version 3.2.4 is out, can you retry? `pipx reinstall organize-tool`

Works now :)

**Comment by feather42** [comment]
Wow that was quick. 
I have reinstalled as directed and now organize --help works as expected.

Thanks for the support.

**Comment by tfeldmann** [comment]
No problem and thanks for the donation! Have a nice day :)
