### ISSUE TITLE
EPUB Extension Support

### ISSUE THREAD

**Issue by ghzgod** [tfeldmann/organize#415]
Hello.  First off I want to say thank you for an amazing tool.  This really helps me a lot on my day to day.  I was reading your documentation and did not see an easy way to parse EPUB files.  Is this going to have support in the future?  It looks like it might be possible by using python3 but I have not had time to explore this in depth yet.  

Thank you and keep up the good work!

**Comment by tfeldmann** [comment]
Thanks for the kind words! In the upcoming version you can use the `exif` filter to extract author, description, identifier, language etc. 👍

**Comment by tfeldmann** [comment]
Update is out. Make sure you have `exiftool` installed and the `ORGANIZE_EXIFTOOL_PATH` is set (https://organize.readthedocs.io/en/latest/filters/#exif). Now you can use the `exif` filter to extract epub metadata.

**Comment by ghzgod** [comment]
Thank you!!!!!
