### ISSUE TITLE
Loosen pdfminer-six Version Constraint for Better Compatibility on NixOS

### ISSUE THREAD

**Issue by adfaure** [tfeldmann/organize#422]
First, thanks for this great project! I’ve been using Organize to sort my photo shoots, and it’s been working perfectly so far.

**Is your feature request related to a problem? Please describe.**
I’m on NixOS, where I maintain a personal package for organize (see here: [nix_configuration/pkgs/organize](https://github.com/adfaure/nix_configuration/tree/master/pkgs/organize/default.nix)). Recently, I hit an issue because the latest nixpkgs includes pdfminer-six version 20240706, which isn’t compatible with the strict ^20231228 constraint in organize. This prevents me from upgrading without applying a manual patch.

**Describe the solution you'd like**
It would be great if the pdfminer-six version constraint could be loosened (e.g., >=20231228, <=20240706).

**Describe alternatives you've considered**
Currently, I patch the version constraint directly in my nix setup as a workaround, but it’s not ideal.

**Additional context**
- Here’s where I keep my Nix package for organize: https://github.com/adfaure/nix_configuration/tree/master/pkgs/organize.
- The nix package of pdfminer-six: https://search.nixos.org/packages channel=24.11&from=0&size=50&sort=relevance&type=packages&query=pdfminer-six

Also, maybe we can try to push my package to nixos, we can work on that if you are interested?

Thank you.

**Comment by tfeldmann** [comment]
Thanks for pointing this out, this should be more relaxed.

> Also, maybe we can try to push my package to nixos, we can work on that if you are interested?

Sure! I have no experience with NixOS yet and your package seems to depend on poetry: I'm planning to migrate to the `uv` dependency manager in the near future. Maybe this is something to consider?

**Comment by adfaure** [comment]
Hello,

Thank you for accommodating my request! 😊

Sure, we can wait for this migration.

A new NixOS release just came out, so there’s no rush (they happen every six months).

**Comment by tfeldmann** [comment]
Just uploaded the fix 👌

**Comment by tfeldmann** [comment]
`uv` migration is still work in progress.

**Comment by adfaure** [comment]
Thanks, do you have a branch dedicated to uv ?
