### ISSUE TITLE
You might find this useful

### ISSUE THREAD

**Issue by cryzed** [tfeldmann/organize#5]
Hey, I made something [similar](https://github.com/cryzed/Filemaid) quite a while ago. It supports a few additional filters ("conditions" for Filemaid): [term conditions](https://github.com/cryzed/Filemaid/blob/master/filemaid.py#L66) (collections of conditions with a junctor), [mime conditions](https://github.com/cryzed/Filemaid/blob/master/filemaid.py#L110) based on the file's detected mimetype, [size conditions](https://github.com/cryzed/Filemaid/blob/master/filemaid.py#L161) and something like your regex filter: [path conditions](https://github.com/cryzed/Filemaid/blob/master/filemaid.py#L98) (which matches on the whole path instead, if you have a more complicated folder hierarchy).

If you have no interest in this, feel free to close this issue and sorry for the noise. I thought some of the concepts might be interesting to you and easily adaptable to your project.

**Comment by tfeldmann** [comment]
No noise at all!
It's amazing how similar the codebases are in terms of structure and terminology. I especially like the idea of condition collections and the way you implemented them. Very cool!

If it's okay for you I might use some of your code in the future - with proper attribution of course!
Thank you a lot for reaching out 👍

**Comment by cryzed** [comment]
Of course it's okay, that's why I linked it, feel free to use it however you see fit!
