### ISSUE TITLE
ERROR! 'PosixPath' object has no attribute 'items'

### ISSUE THREAD

**Issue by F5lx6k564f3** [tfeldmann/organize#51]
I get this error:
> ERROR! 'PosixPath' object has no attribute 'items'

Why do I get it and how to solve this? This is my config.yaml:

`rules:`
 ` - folders: ~/Downloads`
       `filters:`
         `- filename:`
             `startswith: "19"`
             `contains:`
         `- "_WF_"`
    `actions:`
      `- rename: "{path.stem}_unread{path.suffix}"`
      `- copy:`
         ` dest: '~/Documents/'`
         ` overwrite: false`
        `  counter_separator: '_'`

Thank you for helping me!

**Comment by tfeldmann** [comment]
Thank you for the bug report! I located the issue and will release a fix as soon as possible.

**Comment by F5lx6k564f3** [comment]
I use the shell command 'mv' alternatively. Good luck fixing it.

**Comment by tfeldmann** [comment]
I just released an update (v1.6.2) to fix this issue. Can you test it again?

**Comment by F5lx6k564f3** [comment]
It works like a charm!
