### ISSUE TITLE
Feature request: Cancel move action if file exists

### ISSUE THREAD

**Issue by hum4nizer** [tfeldmann/organize#54]
Hi!

I would like to request a feature on the move action. I would like to be able to specify the move action to cancel if the matching file already exists on the destination path.

As is now it can make a new file or overwite it, but it can't cancel the operation.

Many thanks for a great program!
Johnny

**Comment by tfeldmann** [comment]
Hi, yes that would definitely make sense. Only thing I'm struggling with at the moment is how to introduce this without breaking old config files. I added it to my todo list 👍

**Comment by hum4nizer** [comment]
Awesome! I really looking forward to the feature. 

Many thanks for the time and effort you put down in the development of this awesome program.

Best regards,
Johnny

**Comment by tfeldmann** [comment]
Hey Johnny, this is now built in!

Have a look at the [`move` action](https://organize.readthedocs.io/en/latest/actions/#move) where you can now define what to do in case of a conflict. Options are `skip`, `overwrite`, `trash`, `rename_new` and `rename_existing`. So `skip` would work for you 👍
