### ISSUE TITLE
Long term - GUI plans

### ISSUE THREAD

**Issue by pantar85** [tfeldmann/organize#6]
This project seems to be something I have been waiting for for years. Its probably way too early in the life cycle to ask this but have you have plans for a GUI? Thank you for your work

**Comment by tfeldmann** [comment]
Yes, I have a GUI for this in mind but it's just too early. In the meantime I can recommend Hazel (macOS) as a very mature application or File Juggler (Windows).

**Comment by pantar85** [comment]
I use file juggler and there is a good few things it can't do, your rules implementation looks for more broad in what it can cover.

Either way, I am looking for something for my how machines which are all Linux based. Thanks anyway, Ill keep an eye out.

**Comment by tfeldmann** [comment]
For Linux organize might be the best solution currently ;) At the moment you have to work directly with the config file but a gui is planned 👍
