### ISSUE TITLE
Filter by content of PDF file

### ISSUE THREAD

**Issue by fgma** [tfeldmann/organize#61]
I've just found this nice little tool which would almost perfectly fit what I need except for filtering based on content of a file. In my particular use case I'd like to move PDF files to different folders based on its text content.

I've found https://github.com/tfeldmann/organize/issues/10 and the related entry in https://github.com/tfeldmann/organize/projects/4 concerning the use of textract.

If there is any interest I might implement this and submit a PR. To prevent unnecessary work I'd like to discuss the implementation before starting. Would integrating textract as a generic solution be OK or are there other ideas?

**Comment by tfeldmann** [comment]
I think textract fits the usecase very well and would be a great addition!

I'd propose `FileContent` as the filter's name and a regular expression as argument? Then the implementation should be relatively straight-forward and quite similar to the `Regex`-filter.

Any other ideas / enhancements?

**Comment by fgma** [comment]
Thanks for your feedback. I try to have a look at it the next days. I will open a PR when I got something working.

**Comment by fgma** [comment]
Merged in https://github.com/tfeldmann/organize/commit/f3145851bf9fb502fb47271c459c85cbf0d9e007
