### ISSUE TITLE
How to run the program

### ISSUE THREAD

**Issue by Gahamelas** [tfeldmann/organize#73]
Hi, 

I am a newbie in all things technical. I have installed the package doing  pip3 install -U organize-tool. How do I run it? I have written "organize" on the Terminal, but this does not work. Thanks in advance!

**Comment by dskaggs** [comment]
@Gahamelas Welcome to the fun (and usually frustrating) world of technology!

When you try to run organize in the Terminal window, do you get any sort of error messages? That will help guide us in helping you.

Organize requires a list of rules of how you want to process files in various directories. That configuration file can be edited by running `organize config` from the Terminal. Have you done that yet?

**Comment by Gahamelas** [comment]
Haha, thanks! Yes, I opened Terminal and typed  pip3 install -U organize-tool (before that I installed python 3.5x). 
Last lines I get after running that install command are as follows:

`Successfully installed EbookLib-0.17.1 Pillow-7.0.0 PyYAML-5.3.1 Send2Trash-1.5.0 SpeechRecognition-3.8.1 XlsxWriter-1.2.8 appdirs-1.4.3 argcomplete-1.10.0 beautifulsoup4-4.8.0 chardet-3.0.4 colorama-0.4.3 docopt-0.6.2 docx2txt-0.8 exifread-2.1.2 extract-msg-0.23.1 imapclient-2.1.0 lxml-4.5.0 olefile-0.46 organize-tool-1.8.1 pdfminer.six-20181108 pendulum-2.1.0 pycryptodome-3.9.7 python-dateutil-2.8.1 python-pptx-0.6.18 pytz-2019.3 pytzdata-2019.3 six-1.12.0 sortedcontainers-2.1.0 soupsieve-2.0 textract-1.6.3 tzlocal-1.5.1 xlrd-1.2.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Then I type:

`:~$ organize config`

And I get:
`-bash: organize: command not found``

Your help is appreciated.
Thanks, 
GM

**Comment by dskaggs** [comment]
Perfect...that helps. One thing that usually helps is to close the Terminal windows and reopen it. That forces the new Terminal window to get a fresh copy of all the paths and should let it find the organize executable.

So, try closing, re-opening Terminal and type `organize config` again.

**Comment by Gahamelas** [comment]
Thanks. However, I get the same error :/ Do you know where organize is installed? I can't find it anywhere on my disk.

**Comment by dskaggs** [comment]
Depending on the OS (various flavors of Linux or macOS), the path can change. I'm not exactly sure, but you might check `/usr/local/lib/python3` and see if it's there. If you see `organize` there, then it sounds like that directory isn't in your path.

**Comment by Gahamelas** [comment]
Organize is at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/organize. How does this info help me to execute it? Thanks.

**Comment by Gahamelas** [comment]
When I do 

`echo $PATH`

I can see how it is in my path.

`/usr/local/fsl/bin:/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/:/Users/gaha/anaconda2/bin:/Users/gaha/anaconda3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/opt/puppetlabs/bin:/usr/local/munki:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`

Still, when I type organize or organice config, I get "command not found".

:(

**Comment by dskaggs** [comment]
I just installed it natively on my Macbook Pro (I usually use my Docker container). The install location was different for me. It installed to `~/Library/Python/3.6/bin`. I was able to run `organize --version` and it output version 1.8.1.

So, sorry but at this point someone more familiar with Python will have to chime in.

**Comment by Gahamelas** [comment]
Thanks, let's see! P.S.: How do you use Docker to install it? I also have Docker but not sure how to install it using it.

**Comment by tfeldmann** [comment]
> Organize is at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/organize. How does this info help me to execute it? Thanks.

And are you sure you installed `organize-tool` and not the `organize`-package?
The correct folder would be `.../site-packages/organize-tool`.

---

Otherwise it seems like something is wrong with your python installation. Which macOS version do you use? Did you use the official python installer?
Can you give us the output of the following commands?
`which python`, `which python3`, `python3 -m pip list`

**Comment by Gahamelas** [comment]
Thanks! When I run the first command I get

```
Usage:   
  /usr/local/bin/python3 -m pip <command> [options]

no such option: -U

```

Then I reinstalled organize-tool after I restarted my computer and this time worked... Not sure if the restart had to do with it. I checked my Terminal history and I had been installing organize-tool, not just "organize". A mystery...

**Comment by Gahamelas** [comment]
One last question: is it possible to place the config file somewhere else like i.e. Dropbox so it is always synchronized with other machines? Thanks.

**Comment by tfeldmann** [comment]
Yes, sure. You can either use a symlink to sync the config file in its default path or specify a path in the dropbox via the `--config-file` command line option or the `ORGANIZE_CONFIG` environment variable.

**Comment by Gahamelas** [comment]
Thanks, is there somewhere where I can learn how to specify the path via ORGANIZE_CONFIG or command line?

**Comment by Gahamelas** [comment]
I have now a list of rules. However, I want to disable some but I don't know exactly where to specify the command to disable them.

Let's take the example:

```
rules:
  - folders: ~/Downloads
    subfolders: true
    filters:
      - extension: pdf
    actions:
      - echo: "Found PDF!"

```

If I run the following:

```
rules:
  - folders: ~/Downloads
    enable d: false
    subfolders: true
    filters:
      - extension: pdf
    actions:
      - echo: "Found PDF!"
```

The rule keeps operating. I am not sure where to place the "enable d: false" line.
Thanks, 
GM

**Comment by tfeldmann** [comment]
Sorry about that. That's a typo in the documentation and I will fix it ASAP. Of course it must be `enabled` without the space before the d.

```yaml
rules:
  - folders: ~/Downloads
    enabled: false
    subfolders: true
    filters:
      - extension: pdf
    actions:
      - echo: "Found PDF!"
```
