### ISSUE TITLE
Use fd/find to search for files and folders instead of glob()

### ISSUE THREAD

**Issue by andreoliwa** [tfeldmann/organize#84]
Hi @tfeldmann.
First, thank you for this awesome project! 🙂 

I have a suggestion/feature request that I'd like to run by you before trying to work on a pull request.

Python `glob()` is not particularly fast.
So my idea would be to replace it internally by calling [fd (A simple, fast and user-friendly alternative to 'find')](https://github.com/sharkdp/fd) or even `find` (which is not that fast, but it is present by default).

[VSCode already did something similar, using ripgrep for its search engine](https://code.visualstudio.com/updates/v1_11#_text-search-improvements).

Rough specs:

- `organize` could have a configuration like `glob_with_fd: true|false` or something similar;
- The app would use `which fd` or something to determine if `fd` is installed, or `which find` to get `find`'s path;
- All calls to `glob()` would use `fd`/`find` internally instead, and return files/folders in the same format as before (`pathlib.Path` or `str`, I'm not sure how is the return type);
- This feature could also be useful for #32 (another pull request I'm waiting for anxiously 😬 , but unfortunately inactive for a while...).

I saw that [you mentioned something about `glob` in your roadmap](https://github.com/tfeldmann/organize/projects/4#card-25594496); maybe you already have something on your mind.

What do you think?
Would you be interested in this feature?

**Comment by tfeldmann** [comment]
Thank you for reaching out and wanting to help! Much appreciated 👍 
That's a good idea and surely would speed things up quite a bit.

The thing is I'm knee deep in the middle of rewriting the core and directory tree walking algorithms at the moment (Pull request #85).
The idea is to use [PyFilesystem ](https://www.pyfilesystem.org) for globbing to support zip files, S3 Buckets, remote file systems via SSH and many others in the future.

So I'd say it would be better to wait a bit until #85 is done. I'll keep this optimization in mind so your idea can be integrated afterwards for local filesystems without much hassle.

I'm keeping this issue open in the meantime.

**Comment by andreoliwa** [comment]
Nice, using `fd/find` seems related to #85 indeed. Looking forward to it.

I also checked the [roadmap](https://github.com/tfeldmann/organize/projects/4)... some cool ideas on your scratchpad. 😉 

Interesting how you also face some similar issues I have on my [Nitpick](https://github.com/andreoliwa/nitpick/) project.
Stuff like:

- [Config file validation](https://github.com/tfeldmann/organize/projects/4#card-25088419);
- [Using a plugin system](https://github.com/tfeldmann/organize/projects/4#card-25088440);
- [Testing on Windows OS](https://github.com/tfeldmann/organize/projects/4#card-25076439).

I would be interested in knowing how you intend to solve those problems in the future. 😄 
You also inspired me to (soon) make public notes on the [GitHub project](https://github.com/andreoliwa/nitpick/projects/1) by using cards (I didn't know about this feature).

Thanks and keep up the nice work! 💪

**Comment by tfeldmann** [comment]
I know this answer is late - but great project! I'll try that out!

I'm closing this issue because I implemented the full PyFilesystem support. Using `find` would be a nice optimization but v2 is already so much faster I don't really see the need for that and it would make the code much more complicated.

So thanks for the issue and maybe you can try the new version. Keep up the good work!
