### ISSUE TITLE
Issue on macOS Big Sur

### ISSUE THREAD

**Issue by pat-s** [tfeldmann/organize#88]
I get the following on every file when I run `organize run`. Maybe something has changed in the os-specific command?

```
  File wkn_A2DTNH_historic.csv:
    - [Trash] ERROR! dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
```

**Comment by tfeldmann** [comment]
Thanks for reporting. I found a similar issue in the dependency and it seems to be a python bug:

https://github.com/arsenetar/send2trash/issues/24
https://bugs.python.org/issue33281

There is not much I can do so I'm closing this issue.

**Comment by philippmayrth** [comment]
I faced the same problem. This is obviously a problem of the dependency however in the meantime the organize config can be modified to still be able to trash files on Big Sur.

First `brew install trash` (Uses AppleScript or a fallback to system APIs)
Then change:
```yaml
    actions:
      - trash
```

to

```yaml
    actions:
      - shell: 'trash "{path}"'
```
