### ISSUE TITLE
Access to environment variables?

### ISSUE THREAD

**Issue by seebi** [tfeldmann/organize#90]
Is it possible to access and use environment variables?

**Comment by tfeldmann** [comment]
You can use environment variables in the `- folders` section and in the `python` and `shell` actions. Where do you need them?

**Comment by seebi** [comment]
I mean I would like to use something like:

```
    actions:
       - copy: '{env.INVOICE_DIR}/{env.DATE}-xxx.pdf'
```

**Comment by tfeldmann** [comment]
Great idea. I will add this to the next version 👍

**Comment by seebi** [comment]
:-) thx

**Comment by tfeldmann** [comment]
Next 15 minutes 🎉

**Comment by seebi** [comment]
hooray!

**Comment by tfeldmann** [comment]
v1.9.1 is released and available on pypi ✌️
The feature is not yet in the documentation but should work exactly like your example.
I added a second variable `{now}` which contains the time the run started. It can be used like this:

```yaml
- echo "{now:%Y-%m-%d}"
```

**Comment by seebi** [comment]
Great.

I've upgraded, and both features work as expected :-)

thx a lot

**Comment by Gahamelas** [comment]
Great! I got this error when upgrading:

"tox 3.20.1 has requirement six>=1.14.0, but you'll have six 1.12.0 which is incompatible"
