### ISSUE TITLE
Filter on mimetypes

### ISSUE THREAD

**Issue by sandersantema** [tfeldmann/organize#94]
Using the following I can filter on mimetypes:
```yaml
  - folders: ~/Downloads
    filters:
      - python: |
          import magic
          import os
          import re
          if not os.path.isfile(path):
              return False
          else:
            with open(path, 'rb') as file:
                buffer = file.read(2048)
                mime = magic.from_buffer(buffer, mime=True)

            regex = re.compile("audio/.*", re.IGNORECASE)
            return bool(regex.match(mime))
    actions:
      - move: ~/Downloads/Audio/
```

But I wonder whether there's a better way to do this. Given that it clutters my config file if I replicate this for all the mime types I'd want to filter and all those import statements can't be efficient either.

**Comment by tfeldmann** [comment]
Currently working on this. See #109

**Comment by tfeldmann** [comment]
This is now included in the latest version 👍
https://organize.readthedocs.io/en/latest/page/filters.html#mimetype
