### ISSUE TITLE
Parallelize Jobs Run

### ISSUE THREAD

**Issue by AutomationD** [tfeldmann/organize#98]
Great tool!

It would be amazing to add ability to run the rules in parallel, so
- Each rule can be executed independently from each other (think like Photo / Video / Audio content)
- File operation can be done more performantly by using multiple CPU threads

Thoughts?

Thank you!

**Comment by tfeldmann** [comment]
That would be great but I guess it's really hard to get right. For example you might have a rule that moves a file to a different folder where another rule picks it up to copy it to a network drive. Right now the rule ordering makes this work but If these two run parallel we have a race condition. But thank you for the suggestion and I'll keep this is mind!

**Comment by AutomationD** [comment]
Thomas, so you're saying that there may be multiple rules (not actions) that are chained together?

What's the practical benefit of this approach?

In my opinion, having ability to parallelize rules (and not actions) won't really affect the workflow, especially if by default this feature is disabled. 

Please let me know what you think.

**Comment by NGenetzky** [comment]
Just split up your config and run the tool in parallel. Feature disabled by default, feel free to opt in.

**Comment by tfeldmann** [comment]
Yes, thats the way to go and super simple. I added a section to the docs: [parallel jobs](https://organize.readthedocs.io/en/latest/configuration/#parallelize-jobs)
