### ISSUE TITLE
move command - force / at end of path. 

### ISSUE THREAD

**Issue by Glutenberg** [tfeldmann/organize#99]
Forgot / at end of path in move command. Files were renamed and not placed in new subfolder. 

Example of Mistake:
actions:
          - move: ~/Downloads/CAD

Moves all files to CAD folder but renames files to CAD1, CAD2, CAD3 etc with no extension. I understand this is a result of how the file system works but is very dangerous, especially with no undo function.  If this is what the user wants, a "force_rename: true" flag should have to be used. 

@tfeldmann if this is something you agree with I would be happy to write the functionality.

**Comment by tfeldmann** [comment]
Oh man, I'm sorry this happened to you. You are right, there should be at least a warning or something like `allow_rename` or `force_rename`.

I'm thinking the warning should be triggered if moved to a file without extension. Maybe even force the slash at the end if no extension is given. What do you think about this?
Undo functionality is on the todo list!

**Comment by alvesman** [comment]
> Oh man, I'm sorry this happened to you. You are right, there should be at least a warning or something like `allow_rename` or `force_rename`.
> 
> I'm thinking the warning should be triggered if moved to a file without extension. Maybe even force the slash at the end if no extension is given. What do you think about this?
> Undo functionality is on the todo list!

I think the "force the slash at the end if no extension is given" would be great. I renamed a bunch of files because of this! No harm done but it was a scary moment :)

**Comment by gabrielcarloto** [comment]
I did the same thing lol thank god it was on downloads folder

**Comment by tfeldmann** [comment]
This should be fixed now in the new v3 alpha. It would be great if you could try that out :) Install infos are in the repo's readme 👍

**Comment by tfeldmann** [comment]
v3 is released!
